packages:
  - 'packages/codegen'
  - 'packages/integrations'
  - 'packages/model'
  - 'packages/query'
  - 'packages/schema'
  - 'packages/vscode'
  - 'examples/model.usage'
  - 'mono/typescript/packages/*'
