packages:
  - 'examples/model-usage-ts'
  - 'mono/typescript/packages/*'
  - 'packages/codegen'
  - 'packages/codegen-api'
  - 'packages/integrations'
  - 'packages/model-runtime-ts'
  - 'packages/query-runtime-ts'
  - 'packages/react'
  - 'packages/schema'
  - 'packages/schema-api'
  - 'packages/vscode'
