packages:
  - 'build-all'
  - 'examples/browser-sqlite'
  - 'extensions/authorization-grammar'
  - 'extensions/mutation-grammar'
  - 'extensions/mutation-codegen'
  - 'mono/typescript/packages/*'
  - 'packages/absurd-sql'
  - 'packages/cache-runtime-ts'
  - 'packages/codegen'
  - 'packages/codegen-api'
  - 'packages/codegen-cli'
  - 'packages/codegen-sql'
  - 'packages/codegen-ts'
  - 'packages/context-runtime-ts'
  - 'packages/grammar-extension-api'
  - 'packages/integration-tests-ts'
  - 'packages/model-runtime-ts'
  - 'packages/mutator-runtime-ts'
  - 'packages/query-runtime-ts'
  - 'packages/react'
  - 'packages/runtime-ts'
  - 'packages/schema'
  - 'packages/schema-api'
  - 'packages/vscode'
