packages:
  - 'examples/model-usage-ts'
  - 'extensions/authorization-grammar'
  - 'extensions/mutation-grammar'
  - 'mono/typescript/packages/*'
  - 'packages/grammar-extension-api'
  - 'packages/codegen'
  - 'packages/codegen-api'
  - 'packages/integrations'
  - 'packages/model-runtime-ts'
  - 'packages/query-runtime-ts'
  - 'packages/react'
  - 'packages/schema'
  - 'packages/schema-api'
  - 'packages/vscode'
